DROP TABLE site_foursquare_venues_activity;
DROP TABLE site_foursquare_venues_activity_old;
DROP TABLE site_instagram_photos;
DROP TABLE site_instagram_photos_indistinct;
DROP TABLE site_instagram_photos_old;
DROP TABLE site_park;
DROP TABLE site_park_flickr_photos;
DROP TABLE site_park_flickr_photos_old CASCADE;
DROP TABLE site_totals;
DROP TABLE site_totals_old;
DROP TABLE site_tweets;
DROP TABLE site_tweets_old;
